### ISSUE TITLE
extension doesn't recognize bigint 

### ISSUE THREAD

**Issue by jreidthompson** [trlorenz/PG-recursively_delete#11]
ERROR:  P0001: ARG_in "<NULL>" is of an unexpected type: bigint[]

tables using BIGSERIAL / bigint for primary keys etc

**Comment by trlorenz** [comment]
Aha, thx. Will be able to look into it by this weekend, I think.

**Comment by trlorenz** [comment]
Hey, @jreidthompson. Took a look. The only way I could get close to reproducing that error was to explicitly cast the id as bigint:

```
ls-dev-smcc=# create table foo(id1 bigint primary key, id2 bigint, bar text);
CREATE TABLE
ls-dev-smcc=# insert into foo values (1, 100, 'moo'), (2, 200, 'goo'), (3, 300, 'poo');
INSERT 0 3
ls-dev-smcc=# select recursively_delete('foo', array[[2::bigint]]);
INFO:  >>> THE TYPE IS bigint[]
ERROR:  ARG_in "{{2}}" is of an unexpected type: bigint[]
CONTEXT:  PL/pgSQL function recursively_delete(regclass,anyelement,boolean) line 52 at RAISE
```
Without the explicit typecast, it works as expected:

```
ls-dev-smcc=# select recursively_delete('foo', array[[2]]);
INFO:  >>> THE TYPE IS integer[]
INFO:  DAMAGE PREVIEW (recursively_delete v0.1.4)
INFO:  
INFO:          1     foo
INFO:  
 recursively_delete 
--------------------
                  0
(1 row)

ls-dev-smcc=# select recursively_delete('foo', array[2]);
INFO:  >>> THE TYPE IS integer[]
INFO:  DAMAGE PREVIEW (recursively_delete v0.1.4)
INFO:  
INFO:          1     foo
INFO:  
 recursively_delete 
--------------------
                  0
(1 row)

ls-dev-smcc=# select recursively_delete('foo', 2);
INFO:  >>> THE TYPE IS integer
INFO:  DAMAGE PREVIEW (recursively_delete v0.1.4)
INFO:  
INFO:          1     foo
INFO:  
 recursively_delete 
--------------------
                  0
(1 row)
```

But I assume you weren't using ::bigint in your call. Can you provide a little more info so I can reproduce on my side?

**Comment by jreidthompson** [comment]
[local]:5432 rthompso@ateb=> create table foo(id1 bigint primary key, id2 bigint, bar text);create table foo(id1 bigint primary key, id2 bigint, bar text);
CREATE TABLE
ERROR:  42P07: relation "foo" already exists
LOCATION:  heap_create_with_catalog, heap.c:1101
[local]:5432 rthompso@ateb=> \d foo
                Table "public.foo"
 Column |  Type  | Collation | Nullable | Default 
--------+--------+-----------+----------+---------
 id1    | bigint |           | not null | 
 id2    | bigint |           |          | 
 bar    | text   |           |          | 
Indexes:
    "foo_pkey" PRIMARY KEY, btree (id1)

[local]:5432 rthompso@ateb=> select * from foo;
 id1 | id2 | bar 
-----+-----+-----
(0 rows)

[local]:5432 rthompso@ateb=> insert into foo values (1, 100, 'moo'), (2, 200, 'goo'), (3, 300, 'poo');
INSERT 0 3
[local]:5432 rthompso@ateb=>  select recursively_delete('public.foo', (SELECT array_agg(id1) FROM public.foo) ,false);
ERROR:  P0001: ARG_in "{1,2,3}" is of an unexpected type: bigint[]
CONTEXT:  PL/pgSQL function recursively_delete(regclass,anyelement,boolean) line 52 at RAISE
LOCATION:  exec_stmt_raise, pl_exec.c:3848
[local]:5432 rthompso@ateb=>

**Comment by trlorenz** [comment]
Thanks much. Please give trl-fix-unexpected_type_bigint a try when you get a chance.

**Comment by jreidthompson** [comment]
Apologies, I got tied up in other things and forgot about this.  I have verified that the changes correct the issue.  thanks

**Comment by trlorenz** [comment]
No worries, thanks!
