### ISSUE TITLE
How to specify arg type ::uuid?

### ISSUE THREAD

**Issue by fpedroza** [trlorenz/PG-recursively_delete#3]
I can't get this to work with a uuid parameter.

`select recursively_delete('primer.user', '6f5b4ecd-27a3-49c2-bedb-5f9fcfbb8fa1'::uuid);`

> [P0001] ERROR: ARG_in "6f5b4ecd-27a3-49c2-bedb-5f9fcfbb8fa1" is of an unexpected type: uuid Where: PL/pgSQL function recursively_delete(regclass,anyelement,boolean) line 50 at RAISE

This also doesn't work:

`select recursively_delete('primer.user', '6f5b4ecd-27a3-49c2-bedb-5f9fcfbb8fa1');`

> [42804] ERROR: could not determine polymorphic type because input has type unknown

Nor this:

`select recursively_delete('primer.user', '6f5b4ecd-27a3-49c2-bedb-5f9fcfbb8fa1'::text);`

> [42601] ERROR: syntax error at or near "f5b4ecd" Where: PL/pgSQL function recursively_delete(regclass,anyelement,boolean) line 175 at OPEN

Any thoughts/suggestions?

**Comment by trlorenz** [comment]
Hopefully won't be too much of a problem -- I'll have a look this weekend.

**Comment by trlorenz** [comment]
@fpedroza Mind giving https://github.com/trlorenz/PG-recursively_delete/pull/4 a try?

**Comment by trlorenz** [comment]
Closing after merging https://github.com/trlorenz/PG-recursively_delete/pull/4. Will address any inter-schema-related issues mentioned in that PR separately.
