### ISSUE TITLE
`VIEWs` should not contain an `ORDER BY`

### ISSUE THREAD

**Issue by davidfetter** [trlorenz/PG-recursively_delete#6]
...as this is an optimization fence.

**Comment by trlorenz** [comment]
Happy to remove the ORDER BY, but kindly explain. Are you saying that an ORDER BY in a view places a limit on the optimization of the view itself?

I'll have to move the ORDER BY to where the view is used in the procedure (at least for generation of the preview). Is this a wash, or is there still an optimization benefit?

**Comment by davidfetter** [comment]
The `ORDER BY`, as I understand it, does a lot to gum up the works when it comes to bringing the view in-line, and yes, in the specific case of that one place that one function calls it, you'd need an `ORDER BY`. I had looked at the view as possibly being useful in other contexts.

**Comment by davidfetter** [comment]
Thanks!
